name: Weekly Balance Check

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:

jobs:
  check-balance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - run: pip install -r requirements.txt

      - run: python check.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
